###############################################################################
## 公共配置
###############################################################################
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  profiles:
    active: dev
  application:
    name: spring-social
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
      resolve-lazily: false
      location: /Users/yangkai.shen/Documents/code/back-end/spring-boot-demo/spring-boot-demo-upload/tmp
  mvc:
    async:
      request-timeout: 5000

baseUrl: https://www.tmmtmm.online